# base svd model path
base_model_path: stabilityai/stable-video-diffusion-img2vid-xt-1-1

# checkpoint path
ckpt_path: models/MimicMotion_1-1.pth

batch:
  video_folder: assets/bad_videos/bad_videos

test_case:
  - ref_video_path: assets/bad_videos/qa3zximsaj.mp4
    ref_image_path: assets/example_data/images/test2.jpg
    num_frames: 8 
    resolution: 576
    frames_overlap: 6
    num_inference_steps: 25
    noise_aug_strength: 0
    guidance_scale: 2.0
    sample_stride: 2
    fps: 15
    seed: 42


